set_value:
  target:
    entity:
      integration: connectlife
      domain: sensor
  fields:
    value:
      required: true
      selector:
        number:
set_action:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: connectlife
    action:
      required: true
      selector:
        select:
          translation_key: actions
          options:
            - "1"
            - "2"
            - "3"
            - "4"
update:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: connectlife
    data:
      required: true
      example: |
        Delay_start_status: 1
        Delay_start_time: 4
      selector:
        object:
